import sqlite3

conn = sqlite3.connect("chatbot.db")
cursor = conn.cursor()

faq_data = [
    ("hello", "Hi there! How can I assist you today?"),
    ("what is your name", "I am your AI-powered chatbot."),
    ("how are you", "I’m doing great, thanks for asking! How can I help you?"),
    ("what services do you provide", "I can assist with customer support, FAQs, and general queries."),
    ("how to contact support", "You can contact support via email at support@example.com."),
    ("what are your working hours", "We are available 24/7 to assist you."),
    ("where are you located", "Our headquarters is in Chennai, India."),
    ("how do I reset my password", "Click on 'Forgot Password' at login and follow the instructions."),
    ("do you store my data", "Yes, but only to improve our services and securely as per our privacy policy."),
    ("thank you", "You're welcome! Happy to help anytime.")
    ("how do i change my password", "Go to your account settings and select 'Change Password'."),
    ("why am i not receiving otp", "Please wait a moment and try resending the OTP."),
    ("how to delete my account", "Go to Privacy Settings and click Delete Account."),
    ("how to update my email", "You can update your email from your profile settings."),
    ("how to update phone number", "Go to Edit Profile and enter your new phone number."),
    ("my otp is not working", "Please ensure your number is active and try again."),
    ("how do i update my profile", "Go to Profile → Edit Profile to update your details."),
    ("can i recover my old account", "Yes, enter your previous email or phone number to recover it."),
    ("why is my account locked", "Your account may be temporarily locked for security reasons."),
    ("how do i enable two factor authentication", "Go to Security Settings and enable 2FA."),
    ("why is the app slow", "Please restart the app or clear your cache."),
    ("app is not opening", "Try reinstalling or updating to the latest version."),
    ("why is my app crashing", "Ensure you have the latest version and enough storage."),
    ("how to clear cache", "Go to App Settings → Storage → Clear Cache."),
    ("how to update the app", "Visit the Play Store or App Store and tap Update."),
    ("app is not responding", "Please force close and reopen the app."),
    ("im facing technical issues", "Please describe the issue so I can assist you."),
    ("why am i logged out automatically", "This may happen due to security updates."),
    ("my screen freezes", "Restart the app and check your internet connection."),
    ("how do i report a technical problem", "Use the 'Report Issue' option from the Help section."),
    ("how do i track my order", "Go to Orders and click Track Order."),
    ("where is my order", "Please provide your order ID to check its status."),
    ("my order is delayed", "We apologize for the delay; please share your order ID."),
    ("order not delivered", "Please provide your order number so I can check this."),
    ("how long does delivery take", "Delivery takes 3 to 5 business days."),
    ("can i track my shipment", "Yes, tracking is available in your Orders section."),
    ("my order is stuck", "Please share the order ID for details."),
    ("courier not contacted me", "The courier usually contacts before delivery."),
    ("my delivery is marked complete but not received", "We apologize; please raise a complaint immediately."),
    ("how do i schedule delivery", "You can schedule delivery during checkout."),
    ("can i cancel my order", "Yes, you can cancel before the order is shipped."),
    ("how do i cancel", "Go to Orders → Select Order → Cancel."),
    ("order cancellation failed", "Cancellation may fail if the order is already shipped."),
    ("can i modify an order", "Modifications are not allowed after placing the order."),
    ("can i change the size after ordering", "Size changes are not possible after confirmation."),
    ("can i update quantity", "Quantity cannot be updated after placing the order."),
    ("how to cancel a prepaid order", "Follow the same steps as normal cancellation."),
    ("can i re-order the same product", "Yes, click Reorder from your previous orders."),
    ("how do i check cancellation status", "Visit Orders → Cancellation Details."),
    ("can i request a stop shipment", "Stop shipment is possible only before dispatch."),
    ("how do i return a product", "Go to Orders → Select Item → Request Return."),
    ("what is return policy", "Items can be returned within 7 to 10 days of delivery."),
    ("can i return used products", "Returns are accepted only in unused condition."),
    ("return request rejected", "This may be due to policy violations."),
    ("how long does pickup take", "Pickup happens within 2 to 3 business days."),
    ("where is my refund", "Refunds are processed after return verification."),
    ("refund not received", "Please wait 3 to 7 business days for bank processing."),
    ("how to check refund status", "Go to Wallet → Refund Status."),
    ("can i exchange my product", "Yes, exchange is available for selected items."),
    ("can i return without packaging", "Original packaging is required for returns."),
    ("what payment methods are accepted", "We accept UPI, cards, wallets, and net banking."),
    ("payment failed", "Payment may fail due to network issues."),
    ("amount deducted but order not placed", "The amount will be refunded automatically."),
    ("can i pay cash on delivery", "Yes, COD is available in selected locations."),
    ("how do i add a new payment method", "Go to Payment Settings to add a method."),
    ("why is my card not working", "Please check if your bank has blocked online payments."),
    ("upi not working", "Ensure your UPI app is active and linked."),
    ("card payment declined", "This could be due to insufficient balance."),
    ("can i change the payment method", "Payment method cannot be changed after ordering."),
    ("is emi available", "Yes, EMI is available for eligible items."),
    ("how do i update address", "Go to Address Book to update your address."),
    ("can i change address after ordering", "Address can be changed only before shipping."),
    ("why is my pincode not serviceable", "The courier may not operate in your area."),
    ("how to add new address", "Go to Profile → Address → Add New Address."),
    ("delivery address wrong", "Please update it before order dispatch."),
    ("can i set multiple addresses", "Yes, you can save multiple addresses."),
    ("how to set default address", "Select an address and mark it as default."),
    ("delivery boy not contacted me", "They usually contact before arrival."),
    ("delivery attempt failed", "Please ensure your phone is reachable."),
    ("my area is not showing", "Try entering your pincode manually."),
    ("how to download invoice", "Go to Orders and click Download Invoice."),
    ("can i get gst invoice", "Yes, GST invoice is available for eligible products."),
    ("invoice not available", "It will be generated after product is shipped."),
    ("details missing on invoice", "Please contact support to fix invoice errors."),
    ("can i update invoice details", "Invoice details cannot be changed after generation."),
    ("how do i print invoice", "Download it as PDF and print."),
    ("where can i find order id", "Your order ID is listed in your Orders section."),
    ("invoice wrong", "Please raise a ticket for correction."),
    ("can i get invoice by email", "Yes, invoices are emailed upon request."),
    ("why invoice not showing", "Try refreshing the Orders page."),
    ("how do i talk to an agent", "You can request a human agent anytime."),
    ("can i speak to customer care", "Yes, connect through the Help Center."),
    ("how long is the wait time", "Wait times are usually less than 2 minutes."),
    ("can i schedule a call", "Yes, you can request a callback."),
    ("agent not responding", "Please try again after a few minutes."),
    ("how do i submit feedback", "Go to Feedback section and submit your review."),
    ("how do i raise a complaint", "Use the 'Raise Complaint' option."),
    ("where is support email", "You can email us at support@example.com."),
    ("do you offer live chat", "Yes, live chat is available 24/7."),
    ("how to check ticket status", "Go to Tickets → View Status."),
    ("is my data safe", "Yes, your data is protected using encryption."),
    ("how do i report a scam", "Please email details to security@example.com."),
    ("why was i logged out", "This may occur due to security verification."),
    ("how to check privacy policy", "Visit the Privacy section in the app."),
    ("what data do you collect", "We collect basic information to improve service."),
    ("can i disable data sharing", "Yes, go to Privacy Settings to disable it."),
    ("how to report a bug", "Use the Bug Report option in settings."),
    ("my account hacked", "Please reset your password immediately."),
    ("how do i block a user", "Go to the user's profile and tap Block."),
    ("why do you need my location", "Location helps improve delivery accuracy."),
    ("can i get discount", "Please check ongoing offers in the Deals section."),
    ("how to apply coupon", "Enter your coupon code at checkout."),
    ("coupon not working", "The coupon may be expired or not applicable."),
    ("can i use multiple coupons", "Only one coupon is allowed per order."),
    ("where to find offers", "Check the Offers page in the app."),
    ("how do i use cashback", "Cashback is automatically applied during checkout."),
    ("why is my cashback missing", "Cashback appears after successful delivery."),
    ("do you offer student discounts", "Student discounts are available on selected items."),
    ("where is my reward points", "Reward points show up in your Wallet."),
    ("can i transfer my rewards", "Rewards cannot be transferred."),
    ("how to log out", "Go to Settings → Logout."),
    ("how to login", "Enter your registered email or phone and password."),
    ("forgot password", "Click Forgot Password on the login page."),
    ("forgot email", "Try logging in with your phone number."),
    ("cant login", "Please check your credentials and try again."),
    ("i want to change login method", "You can login using OTP or password."),
    ("account suspended", "Please contact support for reactivation."),
    ("why cant i log in", "Your account may be temporarily locked."),
    ("login error", "Try again after restarting the app."),
    ("session expired", "Please login again to continue."),
    ("bye", "Goodbye! Let me know if you need help anytime."),
    ("thanks", "You're welcome! Happy to assist."),
    ("thank you so much", "Always here to help!"),
    ("good morning", "Good morning! How may I assist you today?"),
    ("good night", "Good night! Feel free to reach out anytime."),
    ("hi", "Hello! How can I help you today?"),
    ("is anyone there", "Yes, I’m here to assist you."),
    ("help me", "Sure! Please tell me what you need help with."),
    ("i need assistance", "I'm here to help. What seems to be the issue?"),
    ("what can you do", "I can help with orders, payments, returns, and account issues.")
]

cursor.executemany("INSERT INTO faq (question, answer) VALUES (?, ?)", faq_data)
conn.commit()
conn.close()

print("✅ 10 FAQ entries inserted into chatbot.db")
